### ISSUE TITLE
Hash files

### ISSUE THREAD

**Issue by economoser** [aaowens/PSID.jl#50]
Thanks a lot for the update! Is it expected that the "allfiles_hash.json" file no longer contains a reference to the cross-year individual file for 1968-2021? Previously, it contained the following line:

`"ind2019er.zip": "583e541f2f8d8c9ea12e2f53e8f7594f525d95ad929f5ce804d030e1a593991d"`

**Comment by aaowens** [comment]
No that was a mistake, thanks for noticing. I fixed it.
