### ISSUE TITLE
Handling missing variables from codebook that are present in data and crosswalk files

### ISSUE THREAD

**Issue by maqifrnswa** [aaowens/PSID.jl#53]
First off, thank you! This project is so helpful!

I came across a few variables that are missing from `PSIDcodebook.xml` but are in the data and `psid.xls`. I know you don't maintain any of those files, but it does cause makePSID to error out. Should there be a fallback in those cases? Maybe if it is present in the `.xls`, but not in the `xml`, it still processes everything but leaves the `_label` column blank? I think that's the only consequence of not having the codebook.

Example variables that are missing in the `xml` files but are in the `xls` file:
- V13500 (spouse, race mention 1). Workaround: It's identical to V13501, so I just edited the `xml` file to copy that and changed references to race 2 to race 1
- ER38263A1, ER44236A1, ER39360A1, ER45333A1 (head/reference and spouse "other chronic conditions"). Workaround: These are the same as ER49574 or ER50692.

**Comment by aaowens** [comment]
It is a good idea to not error and leave the `_label` blank. I'll look at it in a week or so.

**Comment by aaowens** [comment]
Fixed in #54
